spring.application.name=inventory
server.servlet.context-path=/inventarios/api/v1
server.port=9090
server.address=0.0.0.0

# Perfil por defecto
spring.profiles.active=local

# --- JPA ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# --- FLYWAY ---
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# --- SECURITY ---
security.jwt.expiration-seconds=28800
